### ISSUE TITLE
Ensure conda-build uses inclusive language

### ISSUE THREAD

**Issue by travishathaway** [conda/conda-build#4494]
### Description

In order to create a welcoming environment for our community, we want to make sure this repository uses inclusive language and avoids problematic terms such as "master" for branch names or "whitelist"/"blacklist" for variable names.

### Linked Issues & PRs

- [x] https://github.com/conda/conda-build/pull/4514 
- [x] https://github.com/conda/conda-build/pull/4531
- [x] Rename `master` branch to `main`
- [x] #4540
- [x] Rename any variables named `black*` to `deny*`
    - @kenodegard not present
- [x] Fix ReadTheDocs config to make sure code is pulled from the correct branch (@jezdez)
- [x] Announcements need to be made in all public channels (conda slack team and conda-forge gitter) with instructions on how people can update their local development environments
    - @kenodegard this may not be necessary since GitHub redirects/announces this for us, see https://github.com/github/renaming
    - [x] @jezdez done for the master/main change in conda/conda-build

**Comment by travishathaway** [comment]
It's important to note that only org owners can make the necessary updates to this repository in order to complete this issue.

**Comment by kenodegard** [comment]
There are two `white*` variables in conda-build, both are recipe keywords: `missing_dso_whitelist` and `runpath_whitelist`.

Both keywords are also in use in `mamaba`/`boa` so we will need to offer similar modifications there.

Furthermore, since conda-build doesn't have an aliasing system like `conda.base.context.Context` does, this becomes a large enough change that I'm wondering if we should backlog the `allow`/`deny` rewording for now?

At the very least, the `allow`/`deny` rewording should be spun off from this epic into a separate effort.
