### ISSUE TITLE
Release 3.22.0

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-build#4542]
### Tasks

- [x] [Complete outstanding PRs](https://github.com/conda/conda-build/milestone/30)
- [x] https://github.com/conda/conda-build/pull/4543
- [x] [Publish release](https://github.com/conda/conda-build/releases/tag/3.22.0)
- [x] Create `3.22.x` branch
- [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/17
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/181
- [x] Handoff to Anaconda packaging team
- [x] Announce release to Twitter

**Comment by kenodegard** [comment]
@bryevdv that's the day we tagged the release here on GH, we are still waiting on the packaging team to make it available (see feedstock links above)

**Comment by kenodegard** [comment]
`conda-build 3.22.0` is now available on both `main` and `conda-forge`.
