### ISSUE TITLE
Pruning the `conda-build` test cases

### ISSUE THREAD

**Issue by sven6002** [conda/conda-build#4590]
### Summary

The testing strategy for the `conda-build` repo is currently outdated and was last maintained thoroughly 6 years ago. So just as (a reference to Star Trek) USS Enterprise underwent multiple refits, redesigns, and upgrade-based missions it was tasked with and the captains that led those missions.

As the orbital shipyard is used for such a purpose URSA team is also updating and re-formatting / redesigning the test cases for `conda-build` right now.

### Tasks
- [x] test_api_build_conda_v2.py **(no pruning required)** @sven6002
- [x] https://github.com/conda/conda-build/pull/4722
- [x] https://github.com/conda/conda-build/pull/4723
- [x] https://github.com/conda/conda-build/issues/4558
- [x] test_api_consistency.py **(no pruning required)** @sven6002
- [x] test_api_convert.py **(no pruning required)** @sven6002
- [x] test_api_debug.py
    - [x] https://github.com/conda/conda-build/pull/4701
    - [x] https://github.com/conda/conda-build/pull/4757
- [x] https://github.com/conda/conda-build/pull/4724
- [x] https://github.com/conda/conda-build/pull/4747
- [x] https://github.com/conda/conda-build/pull/4736
- [x] https://github.com/conda/conda-build/pull/4748
- [x] test_api_test.py **(no pruning required)** @kenodegard
- [x] https://github.com/conda/conda-build/pull/4721
- [x] https://github.com/conda/conda-build/pull/4746
- [x] test_check.py **(no pruning required)** @kenodegard
- [x] https://github.com/conda/conda-build/pull/4749
- [x] test_conda_interface.py **(no pruning required)** @kenodegard
- [x] test_config.py **(no pruning required)** @kenodegard
- [x] https://github.com/conda/conda-build/pull/4729
- [x] https://github.com/conda/conda-build/pull/4741
- [x] https://github.com/conda/conda-build/pull/4739
- [x] test_environ.py **(no pruning required)** @kenodegard
- [x] test_index.py **(no pruning required, to be deprecated in favor of conda-index)** @kenodegard
- [x] test_inspect.py **(no pruning required)** @kenodegard
- [x] https://github.com/conda/conda-build/pull/4744
- [x] https://github.com/conda/conda-build/pull/4683
- [x] https://github.com/conda/conda-build/pull/4745
- [x] https://github.com/conda/conda-build/pull/4728
- [x] https://github.com/conda/conda-build/pull/4727
- [x] https://github.com/conda/conda-build/pull/4743
- [x] https://github.com/conda/conda-build/pull/4730
- [x] https://github.com/conda/conda-build/pull/4725
- [x] https://github.com/conda/conda-build/pull/4731
- [x] https://github.com/conda/conda-build/pull/4726
- [x] https://github.com/conda/conda-build/pull/4738
- [x] https://github.com/conda/conda-build/pull/4737
- [x] https://github.com/conda/conda-build/pull/4735
- [x] test_variant.py
    - [x] https://github.com/conda/conda-build/pull/4720
    - [x] https://github.com/conda/conda-build/pull/4714

### Misc Tasks
- [x] https://github.com/conda/conda-build/issues/4646
- [x] https://github.com/conda/conda-build/pull/4677
- [x] https://github.com/conda/conda-build/pull/4742
- [x] https://github.com/conda/conda-build/pull/4761
