### ISSUE TITLE
Release 3.23.x

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-build#4617]
### Summary

Placeholder for `conda-build 3.23.0` release.

### Tasks

[milestone]: https://github.com/conda/conda-build/milestone/31
[doc]: https://github.com/conda/conda-build/blob/main/RELEASE.md
[main]: https://github.com/AnacondaRecipes/conda-build-feedstock
[conda-forge]: https://github.com/conda-forge/conda-build-feedstock

<details>
<summary>3.23.0</summary>

- [x] [Complete outstanding PRs][milestone]
- [x] Release PR: https://github.com/conda/conda-build/pull/4618
    - See [release process][doc]
- [x] Publish Release: https://github.com/conda/conda-build/releases/tag/3.23.0
- [x] Create`3.23.X` branch
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/19
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/186
- [x] Hand off to the Anaconda packaging team

</details>
<details>
<summary>3.23.1</summary>

- [x] Release PR: https://github.com/conda/conda-build/pull/4639
- [x] Publish Release: https://github.com/conda/conda-build/releases/tag/3.23.1
- [x] Update `3.23.X` branch
- [x] Feedstocks
  - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/21
  - [x] https://github.com/conda-forge/conda-build-feedstock/pull/188
  - [x] https://github.com/conda-forge/conda-build-feedstock/pull/189
- [x] Hand off to the Anaconda packaging team

</details>
<details>
<summary>3.23.2</summary>

- [x] Release PR: https://github.com/conda/conda-build/pull/4661
- [x] Publish release: https://github.com/conda/conda-build/releases/tag/3.23.2
- [x] Update `3.23.X` branch
- [x] Feedstocks
  - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/22
  - [x] https://github.com/conda-forge/conda-build-feedstock/pull/190
- [x] Hand off to the Anaconda packaging team

</details>

- [x] Release PR: https://github.com/conda/conda-build/pull/4669
- [x] Publish release: https://github.com/conda/conda-build/releases/tag/3.23.3
- [x] Update `3.23.X` branch
- [x] Feedstocks
  - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/24
  - [x] https://github.com/conda-forge/conda-build-feedstock/pull/194
- [x] Hand off to the Anaconda packaging team
- [ ] ~Announce release~
    - [ ] ~Slack~
    - [ ] ~Twitter~

**Comment by jezdez** [comment]
Closing this for now since I believe the dust has settled about the release. If needed we can reopen this.
