### ISSUE TITLE
`noarch: True` results in `AttributeError: 'bool' object has no attribute 'lower'`

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-build#4636]
### What happened?

When building a package with `conda-build 2.23.0` and `noarch: True` we get:

```
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 494, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 474, in execute
    outputs = api.build(
  File "/opt/conda/lib/python3.9/site-packages/conda_build/api.py", line 180, in build
    return build_tree(
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 3093, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 2368, in build
    newly_built_packages = bundlers[pkg_type](output_d, m, env, stats)
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 1670, in bundle_conda
    output['checksums'] = create_info_files(metadata, replacements, files, prefix=metadata.config.host_prefix)
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line 1267, in create_info_files
    write_link_json(m)
  File "/opt/conda/lib/python3.9/site-packages/conda_build/build.py", line [113](https://github.com/conda/conda/actions/runs/3488604764/jobs/5841775654#step:3:114)0, in write_link_json
    if noarch_type.lower() == "python":
AttributeError: 'bool' object has no attribute 'lower'
```

Xref https://github.com/conda/conda/actions/runs/3488604764/jobs/5841775654#step:3:133

Looks like some of the stringification removed in https://github.com/conda/conda-build/pull/4603 were necessary.

### Tasks

- [x] Re-review #4603 and identify any other stringifications that need to be restored
- [x] Create a PR patch (https://github.com/conda/conda-build/pull/4637)
- [ ] conda-build 3.23.1 release
- [ ] implement a test for `noarch: True`
