### ISSUE TITLE
Mark conda-build skeleton as "Pending deprecation"

### ISSUE THREAD

**Issue by travishathaway** [conda/conda-build#4640]
### What is the idea?

We eventually want to remove conda-skeleton from conda-build and instead have [Grayskull](https://github.com/conda-incubator/grayskull) be the de facto way for generating new recipes from existing packages.

### What should happen?

To help us achieve this goal, one of the first steps is to mark this feature as "pending deprecation" according to conda's official deprecation policy outlined in [CEP-9](https://github.com/conda-incubator/ceps/blob/main/cep-9.md). 

### Tasks

- [x] When conda-build users run `conda skeleton`, they need to be presented with a "pending deprecation" warning that will link them to the Grayskull project
- [ ] https://github.com/conda-incubator/ceps/pull/17 needs a vote
- [ ] Determine when this will receive the official "deprecation" status.
  - According to CEP-9, the "pending deprecation" status must last at least two regular releases. Do we want even more time for this?

**Comment by mbargull** [comment]
xref: https://github.com/conda-incubator/grayskull/issues/422
It would be helpful to have most of the non-PyPI parts added to Grayskull before or during the deprecation phase and ideally before its final removal, of course.
