### ISSUE TITLE
Simplify maintenance and contribution process

### ISSUE THREAD

**Issue by jezdez** [conda/conda-build#4697]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

In a recent conda community call we were reminded that conda-build has had less focus from the conda maintainer team than conda itself, despite making leaps and bounds to improve the maintenance process.

My guess is that a lack of in-depth experience with conda package building made maintenance more difficult than conda. Plus, many of the use cases and scenarios encoded in conda-build are outside the scope of regular software development and are easier to code review and engage with when being a package builder.

As such, to improve the maintenance of conda-build, we should focus on:

- [ ] Simplifying the maintenance and contributing process further
- [ ] Adding experienced packagers to the maintenance team
- [ ] Tapping into the existing knowledge in the community of using conda-build
- [ ] Having at least one person of the Ursa team skilled up by being mentored in the packaging practitioners

## Short-term

- [ ] Have one person from the conda maintainers being mentored by packaging practitioners (@kenodegard or @travishathaway?)
- [ ] Move conda-build from a federated project status to an own community project team called "build tools" under the conda governance policy
  - [ ] Add more people to "build tools" team from community (like constructor project team)
- [ ] Review testing strategy and implement improvements for better developer experience and test quality and coverage 
  - [ ] Improve the PR template so contributors provide enough information to help the review team understand the context of the request
- [ ] Apply regular release policy (CEP 8) to conda-build
- [ ] Explore and prototype possible applications of a plugin system like conda
- [ ] Execute the deprecation of skeleton and index in conda-build to reduce scope of maintenance (since [Conda Deprecation Schedule CEP](https://github.com/conda-incubator/ceps/pull/27) has passed)
- [ ] Write and vote on CEP to specify the next-gen recipe format (currently: “[boa format](https://github.com/conda-forge/conda-forge.github.io/issues/1612)”), first implemented in boa
  - [ ] Add end user documentation for "boa format"
  - [ ] Add schema for "boa format"
  - [ ] Create a linter for "boa format"
- [ ] Sync with efforts around using conda-build/boa for WASM for emerging platform needs

## Mid-term

- [ ] Implement a plugin infrastructure like conda (CEP 4) and port an existing feature to a plugin
- [ ] Get Anaconda build team to try out next-gen recipe format based on CEP (draft), to get experience and provide feedback to software team
- [ ] Support and interview conda-forge community while trialling next-gen recipe format, to learn about their experience
- [ ] Engage with boa maintainers to expand "build tools" team to also include boa and find common ground (e.g. port code improvements to conda-build, including code quality ;)

## Long-term

- [ ] Write evolution plan for conda-build users and its recipe format(s), and how it relates to other community initiatives like boa
- [ ] Execute migration plan together with community and commercial users

**Comment by kenodegard** [comment]
> And what is this fancy style for issue grouping? 😮

[Tasklists](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-tasklists)

> Is the idea to iterate together, to follow development as it happens, more collaboration?

Yes. Nothing has been decided about the future of conda-build recipes, I expect `meta.yaml` to be supported for the foreseeable future.

> I'm mainly talking about the inconsistencies in the `outputs` feature

There's no reason we cannot address the known issues with `meta.yaml`. During the [ongoing test pruning/review](https://github.com/conda/conda-build/issues/4590) I found several inconsistencies which would be easy to address if we dedicate some time to it.

**Comment by wolfv** [comment]
I just ticked a few items relating to v2 recipe format.
