### ISSUE TITLE
Release 3.24.0

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-build#4795]
### Summary

Placeholder for `conda-build 3.24.0` release.

| Pilot | @jezdez |
|---|---|
| Co-Pilot | @kenodegard |

### Linked Issues & PRs

[milestone]: https://github.com/conda/conda-build/milestone/33
[process]: https://github.com/conda/conda-build/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-build/releases
[main]: https://github.com/AnacondaRecipes/conda-build-feedstock
[conda-forge]: https://github.com/conda-forge/conda-build-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda-build/

- [x] [Complete outstanding PRs][milestone]
- [x] Create release PR
    - https://github.com/conda/conda-build/pull/4801 
    - See [release process][process]
- [x] [Publish Release][releases] https://github.com/conda/conda-build/releases/tag/3.24.0
- [x] Create/update `3.24.x` branch
- [x] Activate the `3.24.x` branch as a version on [Read The Docs][ReadTheDocs]
- [x] Feedstocks
    - [x] Bump version [Anaconda's main][main] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/25
    - [x] Bump version [conda-forge][conda-forge] https://github.com/conda-forge/conda-build-feedstock/pull/197
    - Link any other feedstock PRs that are necessary
- [x] Hand off to the Anaconda packaging team
- [x] Announce release
    - [x] https://github.com/conda/communications/pull/12
    - [x] [Discourse](https://conda.discourse.group/t/conda-23-3-1-conda-build-3-24-0-releases/241)
    - [x] [Twitter](https://twitter.com/condaproject/status/1641739612430434304?s=20)
    - [x] [Matrix](https://matrix.to/#/!SgckMCYyQUhdyooKZe:gitter.im/$15xAmOvqMImZOn1EymcXOXiyaY39mxf_qmAEKGG7MfE?via=gitter.im&via=matrix.org&via=cadair.com)
