### ISSUE TITLE
Release 3.26.0

### ISSUE THREAD

**Issue by beeankha** [conda/conda-build#4926]
### Summary

| Pilot | @beeankha  |
|---|---|
| Co-pilot | @kenodegard  |

### Tasks

<details>
<summary><b>The week before release week</b></summary>

- [x] Create release branch named [`3.26.x`](https://github.com/conda/conda-build/tree/3.26.x)
- [x] Ensure release candidates are being successfully built (see [`conda-canary/label/rc-conda-build-3.26.x`](https://anaconda.org/conda-canary/conda-build/files?channel=rc-conda-build-3.26.x))
- [x] [Complete outstanding milestone items](https://github.com/conda/conda-build/milestone/35)
- [x] Manual testing completed by @kenodegard 

</details>

<details open>
<summary><b>Release week</b></summary>

- [x] Create release PR (see [release process](https://github.com/conda/conda-build/blob/main/RELEASE.md)) https://github.com/conda/conda-build/pull/4937
- [x] [Publish release](https://github.com/conda/conda-build/releases/tag/3.26.0
)
- [x] https://github.com/conda/conda-build/pull/4941
- [x] Activate the `3.26.x` branch on [ReadTheDocs](https://readthedocs.com/projects/continuumio-conda-build/)
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/28
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/204
- [x] Hand off to the Anaconda packaging team
- [x] Announce release
    - Blog post
        - [x] https://github.com/conda-incubator/conda-dot-org/pull/158
        - [x] https://conda.org/blog/2023-07-28-july-2023-releases
    - Long form
        - [x] https://github.com/conda/communications/pull/20
        - [x] [Discourse](https://conda.discourse.group/t/conda-23-7-2-conda-build-3-26-0-conda-libmamba-solver-23-7-0-conda-package-streaming-0-9-0-and-conda-package-handling-2-2-0-releases/361/2)
        - [x] [Matrix `conda/conda`](https://matrix.to/#/!SgckMCYyQUhdyooKZe:gitter.im/$3C2MoteRcEDIghkdfSChrGBS8uO1cbyLd-BKAy1pbNo?via=gitter.im&via=matrix.org&via=salt-rock-lamp.ems.host) (this auto posts from Discourse)
    - Summary
        - [x] [Twitter](https://twitter.com/condaproject/status/1688603431274184704)
        - [x] [Matrix (conda/conda-release)](https://matrix.to/#/!DDdyObfFXiuiRqHyFO:matrix.org/$jYt1YyrHopTDqIDXBFkgy8yJIHO34sCxPslthsTbPYs?via=matrix.org&via=gitter.im)

</details>

**Comment by beeankha** [comment]
All task list items are complete! 🎉
