### ISSUE TITLE
Release 3.26.1

### ISSUE THREAD

**Issue by dholth** [conda/conda-build#4969]
### Summary

Placeholder for `conda-build 3.26.1` release.

| Pilot | @jezdez  |
|---|---|
| Co-pilot | @dholth  |

### Tasks

[milestone]: https://github.com/conda/conda-build/milestone/3.26.1
[process]: https://github.com/conda/conda-build/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-build/releases
[main]: https://github.com/AnacondaRecipes/conda-build-feedstock
[conda-forge]: https://github.com/conda-forge/conda-build-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda-build/

#### The week before release week

- [x] Create release branch (named `YY.M.x`)
- [x] Ensure release candidates are being successfully built (see `conda-canary/label/rc-conda-build-YY.M.x`)
- [x] [Complete outstanding PRs][milestone]
    - [x] #4953
- [x] Test release candidates
    

#### Release week

- [x] Create release PR (see [release process][process])
- [x] [Publish release][releases]: https://github.com/conda/conda-build/releases/tag/3.26.1
- [x] Activate the `YY.M.x` branch on [ReadTheDocs][ReadTheDocs]
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/29
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/30
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/206
    
- [x] Hand off to the Anaconda packaging team
- [x] ~Announce release~
