### ISSUE TITLE
Switch from SemVer to CalVer (i.e., adopt CEP-8)

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-build#4975]
### Summary

We wish to follow in conda's footsteps and adopt the same CalVer outlined in [CEP-8](https://github.com/conda-incubator/ceps/blob/main/cep-8.md).

We desire to make this change since the current SemVer has lost most of its meaning (3.26 means what exactly in relation to all previous versions?). We’re already following the deprecation schedule outlined in [CEP-9](https://github.com/conda-incubator/ceps/blob/main/cep-9.md) so our versioning no longer needs to indicate breakage (see [CEP-8](https://github.com/conda-incubator/ceps/blob/main/cep-8.md) for the full reasoning used for conda).

```[tasklist]
### Notify Downstream Teams
- [x] [Matrix Conda Build Tools Channel](https://matrix.to/#/!zjZSkaZgcvxBwdCKne:matrix.org/$cVXIzhtJvTkLr9cHpXGvO8ntA_2bthMfBCPS0quZ9zU?via=matrix.org&via=mozilla.org)
- [x] Anaconda Packaging Team ([Slack thread](https://anaconda.slack.com/archives/C049N05A2R2/p1701185139492609))
- [ ] Conda-forge
- [ ] Bioconda
- [ ] Others?
```

```[tasklist]
- [x] Decide which release the switch will occur (January 2024)
- [ ] Amend CEP-8 to specify that conda-build will adopt the policy
```

**Comment by kenodegard** [comment]
`conda-build 24.1.0` has been released
