### ISSUE TITLE
Release 3.27.x

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-build#5011]
### Summary

Placeholder for `conda-build 3.27.x` release.

| Pilot | @kenodegard |
|---|---|
| Co-pilot | @jezdez |

### Tasks

[milestone]: https://github.com/conda/conda-build/milestone/36
[process]: https://github.com/conda/conda-build/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-build/releases
[main]: https://github.com/AnacondaRecipes/conda-build-feedstock
[conda-forge]: https://github.com/conda-forge/conda-build-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda-build/

<details>
<summary><h4>The week before release week</h4></summary>

- [x] Create release branch (named `3.27.x`)
- [x] Ensure release candidates are being successfully built (see `conda-canary/label/rc-conda-build-3.27.x`) (https://github.com/conda/conda-build/pull/5012)
- [x] [Complete outstanding PRs][milestone]
- [x] Test release candidates
    - [x] #4183
    - [x] #4184
    - [x] #4945
    - [x] #4943
    - [x] #4953
    - [x] #4965
    - [x] #4964
    - [x] #4957
    - [x] #4986
    - [x] #4960
    - [x] #5004
    - [x] #5006
    - [x] #4942
    - [x] #4930
    - [x] #5008
    - [x] #4813
    - [x] #5005

</details>

#### Release week

- [x] Create release PR (https://github.com/conda/conda-build/pull/5013)
- [x] [Publish release][releases] https://github.com/conda/conda-build/releases/tag/3.27.0
- [x] https://github.com/conda/conda-build/pull/5017
- [x] Activate the `3.27.x` branch on [ReadTheDocs][ReadTheDocs]
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/31
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/207
    
- [x] Hand off to the Anaconda packaging team
- [ ] Announce release
    - Blog Post (optional)
        - [x] conda.org https://github.com/conda-incubator/conda-dot-org/pull/163
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [x] [Twitter](https://twitter.com/condaproject) https://x.com/condaproject/status/1713912930390208519?s=20
        - [ ] Matrix (conda/conda-release)

**Comment by jezdez** [comment]
The canaries seem to have been built with the same version string as the main branch and overwrote those files, without adding the canary label. So we'll need to trigger another canary build so the version string becomes different from the main canaries.
