### ISSUE TITLE
Adopt expedited CEP-9 deprecation policy

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-build#5064]
### Summary

While we have the deprecation helpers available we haven't formalized when and how deprecations occur in conda-build. This has resulted in deprecations being marked for eventual removal in the fictitious `4.0.0` release.

```[tasklist]
- [ ] https://github.com/conda/conda-build/issues/4975
- [x] Adopt 2 releases deprecation schedule (i.e., the next release marks code as deprecations (not pending deprecation), the subsequent release removes the code) https://github.com/conda/conda-build/pull/5080
- [x] Convert ongoing deprecations to conform with expedited release schedule https://github.com/conda/conda-build/pull/5080
```
