### ISSUE TITLE
Release 3.28.x

### ISSUE THREAD

**Issue by jezdez** [conda/conda-build#5071]
### Summary

Placeholder for `conda-build 3.28.x` release.

| Pilot | @kenodegard |
|---|---|
| Co-pilot | @jezdez |

### Tasks

[milestone]: https://github.com/conda/conda-build/milestone/37
[process]: https://github.com/conda/conda-build/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-build/releases
[main]: https://github.com/AnacondaRecipes/conda-build-feedstock
[conda-forge]: https://github.com/conda-forge/conda-build-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda-build/

<details>
<summary><h4>The week before release week</h4></summary>

- [x] Create release branch (named `3.28.x`)
- [x] Ensure release candidates are being successfully built (see [`conda-canary/label/rc-conda-build-3.28.x`](https://anaconda.org/conda-canary/conda-build/files?channel=rc-conda-build-3.28.x))
- [x] [Complete outstanding PRs][milestone]
- [ ] Test release candidates
    - [x] #5021
    - [x] #5032
    - [x] #5009
    - [x] #5037
    - [x] #5040
    - [x] #4999
    - [x] #5042
    - [x] #5039
    - [x] #5050
    - [x] #5066
    - [x] #5027
    - [x] #4405

</details>

<details>
<summary><h4>Release week</h4></summary>

- [x] Create release PR (see [release process][process]) https://github.com/conda/conda-build/pull/5090
- [x] [Publish release][releases] https://github.com/conda/conda-build/releases/tag/3.28.0
- [x] https://github.com/conda/conda-build/pull/5091
- [x] Activate the `3.28.x` branch on [ReadTheDocs][ReadTheDocs]
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/32
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/210
    
- [x] Hand off to the Anaconda packaging team
- [x] Announce release
    - Blog Post (optional)
        - [x] https://github.com/conda-incubator/conda-dot-org/pull/170
    - Long form
        - [x] https://github.com/conda/communications/pull/24
        - [x] [Discourse](https://conda.discourse.group/) https://conda.discourse.group/t/november-releases-conda-23-11-0-conda-build-3-28-1-and-conda-libmamba-solver-23-11-1/456?u=kenodegard
        - [x] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [x] [Twitter](https://twitter.com/condaproject) https://x.com/condaproject/status/1732830642168340557

</details>

<details>
<summary><h4>Hotfix 3.28.1</h4></summary>

- [x] Merge https://github.com/conda/conda-build/pull/5096
- [x] Merge https://github.com/conda/conda-build/pull/5099
- [x] Create release PR (see [release process][process]) https://github.com/conda/conda-build/pull/5100
- [x] [Publish release][releases] https://github.com/conda/conda-build/releases/tag/3.28.1
- [x] https://github.com/conda/conda-build/pull/5102
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/34
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/211
- [x] Hand off to the Anaconda packaging team

</details>

<details>
<summary><h4>Hotfix 3.28.2</h4></summary>

- [x] Merge https://github.com/conda/conda-build/pull/5116
- [x] Merge https://github.com/conda/conda-build/pull/5112
- [x] Merge https://github.com/conda/conda-build/pull/5108
- [x] Create release PR (see [release process][process]) https://github.com/conda/conda-build/pull/5117
- [x] [Publish release][releases] https://github.com/conda/conda-build/releases/tag/3.28.2
- [x] https://github.com/conda/conda-build/pull/5121
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/35
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/212
- [x] Hand off to the Anaconda packaging team

</details>

<details>
<summary><h4>Hotfix 3.28.3</h4></summary>

- [x] Merge https://github.com/conda/conda-build/pull/5124
- [x] Merge https://github.com/conda/conda-build/pull/5130
- [x] Create release PR (see [release process][process]) https://github.com/conda/conda-build/pull/5128
- [x] [Publish release][releases] https://github.com/conda/conda-build/releases/tag/3.28.3
- [x] https://github.com/conda/conda-build/pull/5132/
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/36
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/213
- [x] Hand off to the Anaconda packaging team

</details>

<details>
<summary><h4>Hotfix 3.28.4</h4></summary>

- [x] Merge https://github.com/conda/conda-build/pull/5141
- [x] Create release PR (see [release process][process]) https://github.com/conda/conda-build/pull/5143
- [x] [Publish release][releases] https://github.com/conda/conda-build/releases/tag/3.28.4
- [x] https://github.com/conda/conda-build/pull/5144
- [x] https://github.com/conda/conda-build/pull/5145
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/37
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/214
- [x] Hand off to the Anaconda packaging team

</details>

**Comment by kenodegard** [comment]
Reopening for `conda-build 3.28.2` patch release

**Comment by kenodegard** [comment]
`conda-build 3.28.3` patch release completed

**Comment by kenodegard** [comment]
reopening for 3.28.4 patch release

**Comment by kenodegard** [comment]
`conda-build 3.28.4` patch release completed
