### ISSUE TITLE
Release 24.1.x

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-build#5134]
### Summary

Placeholder for `conda-build 24.1.0` release.

| Pilot | @jezdez |
|---|---|
| Co-pilot | @kenodegard |

### Tasks

[milestone]: https://github.com/conda/conda-build/milestone/38
[process]: https://github.com/conda/conda-build/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-build/releases
[main]: https://github.com/AnacondaRecipes/conda-build-feedstock
[conda-forge]: https://github.com/conda-forge/conda-build-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda-build/

<details>
<summary><h4>The week before release week</h4></summary>

- [x] Create release branch (named `24.1.x`)
- [x] Ensure release candidates are being successfully built (see `conda-canary/label/rc-conda-build-24.1.x`)
- [x] [Complete outstanding PRs][milestone]
  - [x] https://github.com/conda/conda-build/pull/5150
  - [x] https://github.com/conda/conda-build/pull/5153
  - [x] https://github.com/conda/conda-build/pull/5151
  - [x] https://github.com/conda/conda-build/pull/5074
  - [x] https://github.com/conda/conda-build/pull/5158
  - [x] https://github.com/conda/conda-build/pull/5152
- [x] Test release candidates
    

</details>

<details open>
<summary><h4>Release week</h4></summary>

- [x] https://github.com/conda/conda-build/pull/5149 (see [release process][process])
- [x] https://github.com/conda/conda-build/releases/tag/24.1.0 [Publish release][releases]
- [x] https://github.com/conda/conda-build/pull/5163
- [x] Activate the `24.1.x` branch on [ReadTheDocs][ReadTheDocs]
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/38
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/39
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/215
    
- [x] Hand off to the Anaconda packaging team
- [ ] Announce release
    - Blog Post (optional)
        - [x] https://github.com/conda-incubator/conda-dot-org/pull/175
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)

</details>

<details>
<summary><h4>Hotfix 24.1.1</h4></summary>

- [x] https://github.com/conda/conda-build/issues/5167
- [x] https://github.com/conda/conda-build/pull/5172 (see [release process][process])
- [x] https://github.com/conda/conda-build/releases/tag/24.1.1 [Publish release][releases]
- [x] https://github.com/conda/conda-build/pull/5174
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/40
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/216
- [x] Hand off to the Anaconda packaging team

</details>

<details>
<summary><h4>Hotfix 24.1.2</h4></summary>

- [x] https://github.com/conda/conda-build/issues/5179
- [x] https://github.com/conda/conda-build/pull/5184
- [x] https://github.com/conda/conda-build/pull/5187 (see [release process][process])
- [x] https://github.com/conda/conda-build/releases/tag/24.1.2 [Publish release][releases]
- [x] https://github.com/conda/conda-build/pull/5189
- [x] https://github.com/conda/conda-build/pull/5188
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/41
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/217
- [x] Hand off to the Anaconda packaging team

</details>

**Comment by mbargull** [comment]
There is a small metadata fix in gh-5158 which we should include before tagging.

(gh-5152 would also be convenient to include so we are prepared for necessary changes in `24.3`; if it's too late to include that one, we might just have to handle/carry some workarounds for a couple of months -- so, not optimal, but also acceptable, given the very late submission of that PR :speak_no_evil:...)

**Comment by chebee7i** [comment]
I just installed 24.1.1 and it seems like `conda index` no longer works?
```console
$ conda build --version
conda-build 24.1.1
$ conda index --help

CommandNotFoundError: To use 'conda index', install conda-build.
```
Is this expected?

**Comment by dholth** [comment]
This is not expected. `conda index` should redirect to the new implementation, now or soon.

There is the standalone `conda-index` package which provides `python -m conda_index <directory>`. It has different `python -m conda_index --help` CLI options compared to the older command.

**Comment by kenodegard** [comment]
@chebee7i can you update to the latest version of `conda-index=0.4.0` and see if that fixes it? if not please open a new issue so we can investigate further

**Comment by iamthebot** [comment]
Probably a dumb question but I searched and can't find the answer to this anywhere... is there a reason the conda-forge feedstock for conda-build has such a different version?

**Comment by kenodegard** [comment]
@iamthebot `conda-build` switched from SemVer to CalVer in January, see https://github.com/conda/conda-build/issues/4975 and the [announcement from November](https://conda.org/blog/2023-12-07-november-releases#-special-announcement--1)
