### ISSUE TITLE
Refactor conda_build_test_recipe tests

### ISSUE THREAD

**Issue by kenodegard** [conda/conda-build#5135]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### Summary

Let's fully archive the https://github.com/conda/conda_build_test_recipe repository and host the test data some other way within the conda-build repo.

### Linked Issues & PRs

- [ ] Refactor tests using `conda_build_test_recipe`
- [ ] Move `conda_build_test_recipe` to `conda-archive`
