### ISSUE TITLE
Release 24.3.x

### ISSUE THREAD

**Issue by beeankha** [conda/conda-build#5204]
### Summary

Placeholder for conda-build 24.3.0 release.

| Role | Person |
|---|---|
| Pilot | @beeankha |
| Co-pilot | @jezdez |
| Jumpseat / Pilot in Training | @ForgottenProgramme  |

### Tasks

[milestone]: https://github.com/conda/conda-build/milestone/39
[process]: https://github.com/conda/conda-build/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-build/releases
[main]: https://github.com/AnacondaRecipes/conda-feedstock
[conda-forge]: https://github.com/conda-forge/conda-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda/

#### The week before release week

- [x] Create release branch (named `24.3.x`)
- [x] Ensure release candidates are being successfully built (see `conda-canary/label/rc-conda-build-24.3.x`)
- [x] [Complete outstanding PRs](https://github.com/conda/conda-build/milestone/39)
- [x] Test release candidates
  - [x] #4867
  - [x] #5195 
  - [x] #5196 
  - [x] #5199 
  - [x] #5203 
  - [x] #5208 
  - [x] #5219 
  - [x] #5221 
  - [x] #5228 
  - [x] Tested by @beeankha on `osx-64` and Windows
  - [x] Tested by @jezdez on `osx-arm64` and Windows (x86)
    

#### Release week

- [x] Create release PR (see [release process][process]) https://github.com/conda/conda-build/pull/5240
- [x] [Publish release](https://github.com/conda/conda-build/releases/tag/24.3.0)
- [x] Merge `24.3.x` back into `main` https://github.com/conda/conda-build/pull/5247
- [x] Activate the `24.3.x` branch on [ReadTheDocs][ReadTheDocs]
- [x] Feedstocks
    - [x] Bump version & update dependencies/tests in [Anaconda, Inc.'s feedstock](https://github.com/AnacondaRecipes/conda-build-feedstock) https://github.com/AnacondaRecipes/conda-build-feedstock/pull/42
    - [x] Bump version & update dependencies/tests in [conda-forge feedstock](https://github.com/conda-forge/conda-build-feedstock) https://github.com/conda-forge/conda-build-feedstock/pull/221
    
- [x] Hand off to the Anaconda packaging team
- [x] Announce release
    - Blog Post (optional)
        - [x] conda.org https://github.com/conda-incubator/conda-dot-org/pull/185
    - Long form
        - [x] Create release [announcement draft](https://github.com/conda/communications) https://github.com/conda/communications/pull/27
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] ~[Twitter](https://twitter.com/condaproject)~
        - [x] [bsky.app/profile/condaproject.bsky.social/post/3kp7wwb3prt2v](https://bsky.app/profile/condaproject.bsky.social/post/3kp7wwb3prt2v)
        - [x] [fosstodon.org/@conda/112206935021566289](https://fosstodon.org/@conda/112206935021566289)
        - [x] [linkedin.com/feed/update/urn:li:share:7181245411737706496](https://www.linkedin.com/feed/update/urn:li:share:7181245411737706496/)

**Comment by jakirkham** [comment]
Is there anything still needed here?
