### ISSUE TITLE
Release 24.5.x

### ISSUE THREAD

**Issue by beeankha** [conda/conda-build#5319]
### Summary

Placeholder for `conda-build 24.5.x` release.

| Pilot | @beeankha  |
|---|---|
| Co-pilot | @kenodegard  |
| Pilot-in-training | @ForgottenProgramme |

### Tasks

<details>
<summary><h4>The week before release week</h4></summary>

- [x] Create release branch https://github.com/conda/conda-build/tree/24.5.x
- [x] Ensure release candidates are being successfully built (see [`conda-canary/label/rc-conda-build-24.5.x`](https://anaconda.org/conda-canary/repo/files?type=any&label=rc-conda-build-24.5.x))
- [x] [Complete outstanding PRs](https://github.com/conda/conda-build/milestone/40)
- [x] Tested by @beeankha on Windows, Linux, MacOS Intel, and MacOS Apple Silicon

</details>

<details open>
<summary><h4>Release week</h4></summary>

- [x] Create release PR (see [release process](https://github.com/conda/conda/blob/main/RELEASE.md)) https://github.com/conda/conda-build/pull/5326
- [x] [Publish release](https://github.com/conda/conda/releases) https://github.com/conda/conda-build/releases/tag/24.5.0
- [x] https://github.com/conda/conda-build/pull/5334
- [x] Activate the `24.5x` branch on [ReadTheDocs][ReadTheDocs]
- [x] Bump version & update dependencies/tests feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/43
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/44
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/225
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/226
    
- [x] Hand off to the Anaconda packaging team
- [x] Announce release
    - Blog Post (optional)
        - [x] https://github.com/conda-incubator/conda-dot-org/pull/192
    - Long form 
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] https://github.com/conda/communications/pull/28 (announcement copy PR)
        - [ ] [Twitter](https://twitter.com/condaproject)

</details>

<details open>  
<summary><h4>Patch 24.5.1</h4></summary>

- [x] #5342
- [x] #5267
- [x] Create release PR (see [release process](https://github.com/conda/conda/blob/main/RELEASE.md))
  - [x] https://github.com/conda/conda-build/pull/5357
- [x] [Publish release](https://github.com/conda/conda/releases) https://github.com/conda/conda-build/releases/tag/24.5.1
- [x] https://github.com/conda/conda-build/pull/5358
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/45
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/227
- [x] Hand off to the Anaconda packaging team

</details>
