### ISSUE TITLE
Release 24.7.x

### ISSUE THREAD

**Issue by beeankha** [conda/conda-build#5381]
### Summary

Placeholder for `conda-build 24.7.x` release.

| Pilot | @beeankha   |
|---|---|
| Co-pilot | @kenodegard   |

### Tasks

[milestone]: https://github.com/conda/conda-build/milestone/41
[process]: https://github.com/conda/conda-build/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-build/releases
[main]: https://github.com/AnacondaRecipes/conda-build-feedstock
[conda-forge]: https://github.com/conda-forge/conda-build-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda-build/

<details>  
<summary><h4>The week before release week</h4></summary>

- [x] [Create release branch (named `24.7.x`)](https://github.com/conda/conda-build/tree/24.7.x)
- [x] [Ensure release candidates are being successfully built (see `conda-canary/label/rc-conda-build-24.7.x`)](https://anaconda.org/conda-canary/conda-build/files?channel=rc-conda-build-24.7.x)
- [x] [Complete outstanding PRs](https://github.com/conda/conda-build/milestone/41)
- [ ] Verify release candidates
  - Verified by: @beeankha  on Linux, Windows, Mac M1
  - [ ] ~~#5339~~ (CI related, not necessary to verify)
  - [x] #5264 
  - [x] #5355 
  - [x] #5333 
  - [x] #5359 
  - [x] #5350 
  - [x] #5353 
  - [x] #5354 
  - [x] #5364 
  - [ ] #5216 
  - [x] #5344 
  - [x] #4821 
  - [ ] #5365 
  - [x] #5367 
  - [x] #5369 
  - [ ] #5373 
  - [x] #5370 
  - [ ] #5368 
  - [ ] #5281 
  - [ ] #5384 
  - [x] ~~#5387~~ (CI related, not necessary to verify)
  - [x] #5371 
  - [x] #5393 
  - [x] #5352 
  - [x] #5402 
  - [x] #5404 
  - [ ] #5231 
  - [x] #5406 
  - [ ] #5176 
    

</details>

<details open>  
<summary><h4>Release week</h4></summary>

- [x] Create release PR (see [release process](https://github.com/conda/conda-build/blob/main/RELEASE.md)) https://github.com/conda/conda-build/pull/5418
- [x] [Publish release](https://github.com/conda/conda-build/releases) https://github.com/conda/conda-build/releases/tag/24.7.0
- [x] https://github.com/conda/conda-build/pull/5419
- [x] Activate the `24.7.x` branch on [ReadTheDocs][ReadTheDocs]
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/46
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/228
    
- [x] Hand off to the Anaconda packaging team
- [ ] Announce release
    - Blog Post (optional)
        - [x] https://github.com/conda-incubator/conda-dot-org/pull/194
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)

</details>

<details open>  
<summary><h4>Patch 24.7.1</h4></summary>

- [x] https://github.com/conda/conda-build/issues/5433
- [x] Create release PR (see [release process][process]) https://github.com/conda/conda-build/pull/5435
- [x] [Publish release][releases] https://github.com/conda/conda-build/releases/tag/24.7.1
- [x] https://github.com/conda/conda-build/pull/5436
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/47
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/229
- [x] Hand off to the Anaconda packaging team

</details>

**Comment by h-vetinari** [comment]
There were a couple of regressions in 24.7 that are still present in 24.7.1; it would be nice if we could have a 24.7.2 with those 😇 

@jakirkham [pointed out](https://github.com/conda/conda/issues/13995#issuecomment-2287276192)
> > JFYI have seen some issues with re-rendering using `conda-smithy`, which go away when using `conda-build` version `24.5.1` and appear when using `conda-build` version `24.7.1`. [...]
> > More details in issue: [conda-forge/conda-smithy#2011](https://github.com/conda-forge/conda-smithy/issues/2011)
> 
> Looks like this would be addressed in PR: [conda/conda-build#5458](https://github.com/conda/conda-build/pull/5458)

I've raised a similar issue for this #5443, which should likewise be solved by #5458. The second PR that would be important to have is #5447 which fixes #5445 / https://github.com/conda-forge/conda-smithy/issues/2012.
