### ISSUE TITLE
Release 24.9.x

### ISSUE THREAD

**Issue by beeankha** [conda/conda-build#5481]
### Summary

Placeholder for `conda-build 24.9.x` release.

| Pilot | @beeankha  |
|---|---|
| Co-pilot | @kenodegard |

### Tasks

[milestone]: https://github.com/conda/conda-build/milestone/42
[process]: https://github.com/conda/conda-build/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-build/releases/tag/24.9.0
[main]: https://github.com/AnacondaRecipes/conda-build-feedstock
[conda-forge]: https://github.com/conda-forge/conda-build-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda-build/

<details>  
<summary><h4>The week before release week</h4></summary>

- [x] Create release branch (named `24.9.x`)
- [x] Ensure release candidates are being successfully built (see [`conda-canary/label/rc-conda-build-24.9.x`](https://anaconda.org/conda-canary/repo/files?type=any&label=rc-conda-build-24.9.x))
- [x] [Complete outstanding PRs][milestone]
- [x] Test release candidates
  - Changes verified on Windows, MacOS M1, MacOS Intel, Linux by @beeankha 
  - Linux changes reveiewed by @kenodegard 
    

</details>

<details open>  
<summary><h4>Release week</h4></summary>

- [x] Create release PR (see [release process][process]) https://github.com/conda/conda-build/pull/5484
- [x] [Publish release][releases]
- [x] https://github.com/conda/conda-build/pull/5491
- [x] Activate the `24.9.x` branch on [ReadTheDocs][ReadTheDocs]
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/48
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/230
    
- [x] Hand off to the Anaconda packaging team
- [ ] Announce release
    - Blog Post (optional)
        - [x] https://github.com/conda/conda-dot-org/pull/213
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)

</details>
