### ISSUE TITLE
Release 24.11.x

### ISSUE THREAD

**Issue by beeankha** [conda/conda-build#5524]
### Summary

Placeholder for `conda-build 24.11.x` release.

| Pilot | @beeankha  |
|---|---|
| Co-pilot | @ForgottenProgramme  |
| Jumpseat | @kenodegard |

### Tasks

[milestone]: https://github.com/conda/conda-build/milestone/43
[process]: https://github.com/conda/conda-build/blob/main/RELEASE.md
[releases]: https://github.com/conda/conda-build/releases
[main]: https://github.com/AnacondaRecipes/conda-build-feedstock
[conda-forge]: https://github.com/conda-forge/conda-build-feedstock
[ReadTheDocs]: https://readthedocs.com/projects/continuumio-conda-build/

<details>
<summary><h4>The week before release week</h4></summary>

- [x] Create release branch (named [`24.11.x`](https://github.com/conda/conda-build/tree/24.11.x))
- [x] Ensure release candidates are being successfully built (see [`conda-canary/label/rc-conda-build-24.11.x`](https://anaconda.org/conda-canary/repo/files?type=any&label=rc-conda-build-24.11.x))
- [x] [Complete outstanding PRs][milestone]
- [x] Test release candidates (tested by @beeankha on Windows and MacOS M1)
    - [x] https://github.com/conda/conda-build/pull/5209
    - [x] https://github.com/conda/conda-build/pull/5479
    - [x] https://github.com/conda/conda-build/pull/5502
    - [x] https://github.com/conda/conda-build/pull/5508
    - [x] https://github.com/conda/conda-build/pull/5514
    - [x] https://github.com/conda/conda-build/pull/5517
    - [x] https://github.com/conda/conda-build/pull/5518
    - [x] https://github.com/conda/conda-build/pull/5525
    - [x] https://github.com/conda/conda-build/pull/5528
    - [x] https://github.com/conda/conda-build/pull/5534
    - [x] https://github.com/conda/conda-build/pull/5535

</details>

<details open>  
<summary><h4>Release week</h4></summary>

- [x] Create release PR (see [release process][process]) https://github.com/conda/conda-build/pull/5540
- [x] [Publish release][releases] https://github.com/conda/conda-build/releases/tag/24.11.0
- [x] https://github.com/conda/conda-build/pull/5548
- [x] Activate the `24.11.x` branch on [ReadTheDocs][ReadTheDocs]
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/49
    - [x] ~https://github.com/conda-forge/conda-build-feedstock/pull/231~
    
- [x] Hand off to the Anaconda packaging team
- [x] Announce release
    - Blog Post (optional)
        - [x] https://github.com/conda/conda-dot-org/pull/231
    - Long form
        - [ ] Create release [announcement draft](https://github.com/conda/communications)
        - [ ] [Discourse](https://conda.discourse.group/)
        - [ ] [Matrix (conda/conda)](https://matrix.to/#/#conda_conda:gitter.im) (this auto posts from Discourse)
    - Summary
        - [ ] [Twitter](https://twitter.com/condaproject)

</details>

<details>
<summary><h4>Patch 24.11.1</h4></summary>

- [x] https://github.com/conda/conda-build/pull/5550
- [x] Create release PR (see [release process][process]) https://github.com/conda/conda-build/pull/5552
- [x] [Publish release](https://github.com/conda/conda-build/releases/tag/24.11.1)
- [x] https://github.com/conda/conda-build/pull/5548
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/50
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/232
    
- [x] Hand off to the Anaconda packaging team

</details>

<details>
<summary><h4>Patch 24.11.2</h4></summary>

- [x] https://github.com/conda/conda-build/issues/5416
- [x] Create release PR (see [release process][process]) https://github.com/conda/conda-build/pull/5556
- [x] [Publish release][releases] https://github.com/conda/conda-build/releases/tag/24.11.2
- [x] https://github.com/conda/conda-build/pull/5557
- [x] Feedstocks
    - [x] https://github.com/AnacondaRecipes/conda-build-feedstock/pull/51
    - [x] https://github.com/conda-forge/conda-build-feedstock/pull/235
- [x] Hand off to the Anaconda packaging team

</details>

**Comment by kenodegard** [comment]
Bug reported: https://github.com/conda/conda-build/issues/5549
